Issue_16
tsu-trpo/puckmun pull request #17
Opened 2017-11-28 04:27 UTC by alex8h

Создали функцию изменения ячейки карты

2017-11-28 10:14 UTC, maurges reviewed
И ещё одна важная вещь: стоит более подробно описывать коммиты: говорить, что в них было сделано. Сейчас в ваших коммитах трудно ориентироваться.

2017-11-28 10:14 UTC, d86leader commented on objects/Map.h
> +	void Change_Block(Coordinate,Coordinate, Block);
Я люблю в таких функциях возвращать изменённый объект, то есть *this, рекомендую и вам так сделать.
А ещё мы не называем функции с большой буквы.

2017-11-28 10:14 UTC, d86leader commented on objects/Map.cpp
> +	m_map[width][height] = block;
Нет проверки выхода за границы. Для того чтобы добавить её без проблем, можно вместо `vector#[]` использовать `vector#at`

2017-11-28 10:14 UTC, d86leader commented on objects/Map.cpp
> +void Map::Change_Block(Coordinate height,Coordinate width, Block block)
Кстати, а почему такие интересные названия переменных координат? 🤔

2017-12-12 02:48 UTC, maurges requested changes

2017-12-12 02:48 UTC, d86leader commented on objects/Map.h
> +	Map change_block(Coordinate,Coordinate, Block);
Здесь поскольку нет `&`возвращается не сам изменённый объект, а его копия.
https://ru.stackoverflow.com/questions/178009/%D0%9A%D0%B0%D0%BA-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B8

2017-12-12 02:59 UTC, tatsar commented on objects/Map.h
> +	Map change_block(Coordinate,Coordinate, Block);
сделали https://github.com/tsu-trpo/puckmun/commit/12ee5413056685653f25003e95aa1cdf619c366b#diff-a089326b32b55504ec5161b22895b3f3

2017-12-12 03:11 UTC, maurges submitted a review, later dismissed

2017-12-12 03:13 UTC, d86leader commented
-1 -1 -1

2017-12-13 05:47 UTC, vosafonov reviewed
Я тут ещё подумал. А зачем вам поля `m_height` и `m_width`. Их ведь можно из `m_map` доставать.

Когда есть условно две переменные(`m_map`.size() и `width`), которые по факту обозначают одно и то же, то появляется шанс, что это переменные ошибочно 'разъедутся'. К примеру, одна будет равна 10, а вторая 9.

Можно, кстати, завести вспомогательные методы, которые будут возвращать `height` и `width`, чтобы постоянно не писать `m_map.size()` и `m_map[0].size()`.

2017-12-13 05:47 UTC, vosafonov commented on objects/Map.cpp
> +	if(height >= 0 && height < m_height && width >= 0 && width < m_width)
`Coordinate` же `size_t`, т.е. не может быть меньше 0. Т.е. можно упростить вот так:
```
if (height < m_height && width < m_width)
```

2017-12-13 05:47 UTC, vosafonov commented on objects/Map.cpp
> +		m_map.at(width).at(height) = block;
А блока `else` нету? Не очень хорошо скрывать от пользователя функции то, что его запрос даже не обработан.

Как вариант: можно бросать исключение.

2017-12-13 07:23 UTC, alex8h commented on objects/Map.cpp
> +	if(height >= 0 && height < m_height && width >= 0 && width < m_width)
https://github.com/tsu-trpo/puckmun/commit/f49b5610c81fd7b6a3eb706179bd772ab08ee701

2017-12-13 07:26 UTC, alex8h commented on objects/Map.cpp
> +		m_map.at(width).at(height) = block;
Мы не обсудили как это будет происходить

2017-12-13 13:20 UTC, vosafonov commented on objects/Map.cpp
> +	return m_map[0].size();
До этой строки ещё нужно блок вставить:
```cpp
if (get_width() == 0) {
    return 0;
}
```

Иначе может быть `segfault`.

2017-12-13 13:20 UTC, vosafonov commented on objects/Map.cpp
> +	if(height < m_map[0].size() && width < m_map.size())
Раз уж появились `get_height` и `get_width`, то нужно их использовать :)

2017-12-13 13:20 UTC, vosafonov commented on objects/Map.cpp
> +		i.resize(height);
Кажется, что тут будет копирование.
Нужно использовать ссылку:
```cpp
for(auto &i : m_map)
```

Иначе этот `resize` выполняется над временным объектом, а элементы из `m_map` так и не изменяются.

2017-12-13 13:20 UTC, vosafonov commented on objects/Map.cpp
> +		i.resize(height);
Ещё, я бы поменял название `i` -> `line`. Т.е. дал более осмысленное имя. `i` по факту ни о чём не говорит.

2017-12-13 15:29 UTC, d86leader commented on objects/Map.cpp
> +		m_map.at(width).at(height) = block;
А мне казалось, мы это обсудили. =0 Прямо точно помню.
Я сказал, что вся эта проверка есть в методе `.at()`, поэтому сам блок `if` не нужен, и исключение бросается само.

2017-12-13 17:40 UTC, vosafonov commented on objects/Map.cpp
> +		m_map.at(width).at(height) = block;
У нас же проверки на границы в `if`е, так что тут вообще нет смысла в `.at()` :)

2017-12-19 03:11 UTC, vosafonov commented on objects/Map.cpp
> +	return m_map[0].size();
`+`

2017-12-19 03:11 UTC, vosafonov commented on objects/Map.cpp
> +	if(height < m_map[0].size() && width < m_map.size())
`+`

2017-12-19 03:11 UTC, vosafonov commented on objects/Map.cpp
> +		i.resize(height);
`+`

2017-12-19 03:20 UTC, vosafonov approved these changes
+1

2017-12-21 10:52 UTC, d86leader commented on objects/Map.cpp
> +	for( auto &line : m_map)
Нужно убрать один пробел и поставить другой: `for (auto ...`

2017-12-21 10:53 UTC, d86leader commented on objects/Map.h
> +	Map & change_block(Coordinate,Coordinate, Block);
В этих двух строках как-то неодинаково пробелы после запятых стоят.

2017-12-21 11:11 UTC, merged